"""phase2_add_columns_and_tables

Revision ID: b226615a3c81
Revises: bb5b5d152b0e
Create Date: 2026-10-02 17:35:57.779390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b226615a3c81'
down_revision: Union[str, None] = 'bb5b5d152b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_sources',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('lead_id', sa.String(length=100), nullable=False),
    sa.Column('source_code', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_code', 'external_id', name='uq_lead_sources_source_external')
    )
    op.create_index(op.f('ix_lead_sources_lead_id'), 'lead_sources', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_sources_source_code'), 'lead_sources', ['source_code'], unique=False)
    op.create_table('query_results',
    sa.Column('query_id', sa.String(length=100), nullable=False),
    sa.Column('lead_id', sa.String(length=100), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('query_id', 'lead_id')
    )
    op.add_column('agent_messages', sa.Column('role', sa.String(length=50), nullable=True))
    op.add_column('agent_messages', sa.Column('tool_trace', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('jobs', sa.Column('params_hash', sa.String(length=64), nullable=True))
    op.add_column('jobs', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('cancel_requested', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('leads', sa.Column('source_code', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('fingerprint', sa.String(length=64), nullable=True))
    op.add_column('leads', sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_leads_source_code'), 'leads', ['source_code'], unique=False)
    op.add_column('queries', sa.Column('decision', sa.String(length=50), nullable=True))
    op.add_column('queries', sa.Column('job_id', sa.String(length=100), nullable=True))
    op.add_column('queries', sa.Column('records_returned', sa.Integer(), nullable=True))
    op.add_column('queries', sa.Column('records_new', sa.Integer(), nullable=True))
    op.add_column('queries', sa.Column('records_updated', sa.Integer(), nullable=True))
    op.add_column('queries', sa.Column('served_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_queries_job_id'), 'queries', ['job_id'], unique=False)
    op.create_foreign_key('fk_queries_job_id', 'queries', 'jobs', ['job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_queries_job_id', 'queries', type_='foreignkey')
    op.drop_index(op.f('ix_queries_job_id'), table_name='queries')
    op.drop_column('queries', 'served_at')
    op.drop_column('queries', 'records_updated')
    op.drop_column('queries', 'records_new')
    op.drop_column('queries', 'records_returned')
    op.drop_column('queries', 'job_id')
    op.drop_column('queries', 'decision')
    op.drop_index(op.f('ix_leads_source_code'), table_name='leads')
    op.drop_column('leads', 'last_seen_at')
    op.drop_column('leads', 'first_seen_at')
    op.drop_column('leads', 'fingerprint')
    op.drop_column('leads', 'external_id')
    op.drop_column('leads', 'source_code')
    op.drop_column('jobs', 'cancel_requested')
    op.drop_column('jobs', 'heartbeat_at')
    op.drop_column('jobs', 'idempotency_key')
    op.drop_column('jobs', 'params_hash')
    op.drop_column('agent_messages', 'tool_trace')
    op.drop_column('agent_messages', 'role')
    op.drop_table('query_results')
    op.drop_index(op.f('ix_lead_sources_source_code'), table_name='lead_sources')
    op.drop_index(op.f('ix_lead_sources_lead_id'), table_name='lead_sources')
    op.drop_table('lead_sources')
    # ### end Alembic commands ###
